package com.wisecoders.jdbc.scylladb

import com.datastax.oss.driver.api.core.CqlSession
import com.datastax.oss.driver.api.core.cql.BatchStatement
import com.datastax.oss.driver.api.core.cql.BatchType
import com.datastax.oss.driver.api.core.cql.BoundStatement
import com.datastax.oss.driver.api.core.cql.PreparedStatement
import com.datastax.oss.driver.api.core.servererrors.SyntaxError
import com.wisecoders.common_jdbc.jvm.sql.setOrGrow
import com.wisecoders.jdbc.scylladb.DateUtil.considerTimeZone
import java.io.InputStream
import java.io.Reader
import java.math.BigDecimal
import java.net.URL
import java.sql.Blob
import java.sql.Clob
import java.sql.Date
import java.sql.NClob
import java.sql.ParameterMetaData
import java.sql.Ref
import java.sql.ResultSet
import java.sql.ResultSetMetaData
import java.sql.RowId
import java.sql.SQLException
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLSyntaxErrorException
import java.sql.SQLXML
import java.sql.Time
import java.sql.Timestamp
import java.util.Calendar

/**
 * Licensed under [CC BY-ND 4.0 DEED](https://creativecommons.org/licenses/by-nd/4.0/), copyright [Wise Coders GmbH](https://wisecoders.com), used by [DbSchema Database Designer](https://dbschema.com).
 * Code modifications allowed only as pull requests to the [public GIT repository](https://github.com/wise-coders/scylladb-jdbc-driver).
 */
class ScyllaDBPreparedStatement internal constructor(
    session: CqlSession,
    private val preparedStatement: PreparedStatement,
    private val returnNullStrings: Boolean
) :
    ScyllaDBBaseStatement(session), java.sql.PreparedStatement {
    private var params = mutableListOf<Any?>()

    override fun executeQuery(): ResultSet {
        return ScyllaDBResultSet(this, session.execute(bindParameters()), returnNullStrings)
    }

    @Throws(SQLException::class)
    override fun executeQuery(sql: String): ResultSet {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun execute(sql: String): Boolean {
        throw SQLException("Method should not be called on prepared statement")
    }

    override fun setObject(
        parameterIndex: Int,
        value: Any
    ) {
        val idx = parameterIndex - 1
        params.setOrGrow(idx, value )
    }

    @Throws(SQLException::class)
    override fun addBatch(sql: String) {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun clearBatch() {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun executeUpdate(): Int {
        checkClosed()
        try {
            result = ScyllaDBResultSet(this, session.execute(bindParameters()), returnNullStrings)
            if (result!!.isQuery) {
                throw SQLException("Not an update statement")
            }
            return 1
        } catch (ex: SyntaxError) {
            throw SQLSyntaxErrorException(ex.message, ex)
        } catch (t: Throwable) {
            throw SQLException(t.localizedMessage, t)
        }
    }

    @Throws(SQLException::class)
    override fun executeUpdate(sql: String): Int {
        throw SQLException("Method should not be called on prepared statement")
    }

    override fun close() {
        super.close()
        if (result != null) {
            result!!.close()
            result = null
        }
    }

    @Throws(SQLException::class)
    override fun getResultSet(): ResultSet? {
        checkClosed()
        return result
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        autoGeneratedKeys: Int
    ): Int {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnIndexes: IntArray
    ): Int {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnNames: Array<String>
    ): Int {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        autoGeneratedKeys: Int
    ): Boolean {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnIndexes: IntArray
    ): Boolean {
        throw SQLException("Method should not be called on prepared statement")
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnNames: Array<String>
    ): Boolean {
        throw SQLException("Method should not be called on prepared statement")
    }

    override fun setNull(
        parameterIndex: Int,
        sqlType: Int
    ) {
    }

    @Throws(SQLException::class)
    override fun setBoolean(
        parameterIndex: Int,
        x: Boolean
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setByte(
        parameterIndex: Int,
        x: Byte
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setShort(
        parameterIndex: Int,
        x: Short
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setInt(
        parameterIndex: Int,
        x: Int
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setLong(
        parameterIndex: Int,
        x: Long
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setFloat(
        parameterIndex: Int,
        x: Float
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setDouble(
        parameterIndex: Int,
        x: Double
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setBigDecimal(
        parameterIndex: Int,
        x: BigDecimal
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setString(
        parameterIndex: Int,
        x: String
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setBytes(
        parameterIndex: Int,
        x: ByteArray
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setDate(
        parameterIndex: Int,
        x: Date
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setTime(
        parameterIndex: Int,
        x: Time
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setTimestamp(
        parameterIndex: Int,
        x: Timestamp
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setAsciiStream(
        parameterIndex: Int,
        x: InputStream,
        length: Int
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Deprecated("Deprecated in Java")
    @Throws(SQLException::class)
    override fun setUnicodeStream(
        parameterIndex: Int,
        x: InputStream,
        length: Int
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setBinaryStream(
        parameterIndex: Int,
        x: InputStream,
        length: Int
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun clearParameters() {
        checkClosed()
        clearParams()
    }

    @Throws(SQLException::class)
    override fun setObject(
        parameterIndex: Int,
        x: Any,
        targetSqlType: Int
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun execute(): Boolean {
        checkClosed()
        try {
            return executeInner(session.execute(bindParameters()), returnNullStrings)
        } catch (t: Throwable) {
            throw SQLException(t.message, t)
        }
    }

    private fun bindParameters(): BoundStatement {
        try {
            return preparedStatement.bind(*params.toTypedArray())
        } finally {
            clearParams()
        }
    }

    private fun clearParams() {
        params.clear()
    }

    @Throws(SQLException::class)
    override fun addBatch() {
        try {
            if (batchStatementBuilder == null) {
                batchStatementBuilder = BatchStatement.builder(BatchType.LOGGED)
            }
            batchStatementBuilder!!.addStatement(preparedStatement.bind(*params.toTypedArray()))
        } catch (t: Throwable) {
            throw SQLException(t.message, t)
        } finally {
            clearParameters()
        }
    }

    @Throws(SQLException::class)
    override fun setCharacterStream(
        parameterIndex: Int,
        reader: Reader,
        length: Int
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setRef(
        parameterIndex: Int,
        x: Ref
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setBlob(
        parameterIndex: Int,
        x: Blob
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setClob(
        parameterIndex: Int,
        x: Clob
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setArray(
        parameterIndex: Int,
        x: java.sql.Array
    ) {
        checkClosed()
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun getMetaData(): ResultSetMetaData {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setDate(
        parameterIndex: Int,
        x: Date,
        cal: Calendar
    ) {
        checkClosed()
        val result = considerTimeZone(x, cal, DateUtil.Direction.TO_UTC)
        setObject(parameterIndex, result)
    }

    @Throws(SQLException::class)
    override fun setTime(
        parameterIndex: Int,
        x: Time,
        cal: Calendar
    ) {
        checkClosed()
        val result = considerTimeZone(x, cal, DateUtil.Direction.TO_UTC)
        setObject(parameterIndex, result)
    }

    @Throws(SQLException::class)
    override fun setTimestamp(
        parameterIndex: Int,
        x: Timestamp,
        cal: Calendar
    ) {
        checkClosed()
        val result = considerTimeZone(x, cal, DateUtil.Direction.TO_UTC)
        setObject(parameterIndex, result)
    }

    @Throws(SQLException::class)
    override fun setNull(
        parameterIndex: Int,
        sqlType: Int,
        typeName: String
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setURL(
        parameterIndex: Int,
        x: URL
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun getParameterMetaData(): ParameterMetaData {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setRowId(
        parameterIndex: Int,
        x: RowId
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNString(
        parameterIndex: Int,
        value: String
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNCharacterStream(
        parameterIndex: Int,
        value: Reader,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNClob(
        parameterIndex: Int,
        value: NClob
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setClob(
        parameterIndex: Int,
        reader: Reader,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setBlob(
        parameterIndex: Int,
        inputStream: InputStream,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNClob(
        parameterIndex: Int,
        reader: Reader,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setSQLXML(
        parameterIndex: Int,
        xmlObject: SQLXML
    ) {
        throw SQLFeatureNotSupportedException()
    }

    override fun setObject(
        parameterIndex: Int,
        x: Any,
        targetSqlType: Int,
        scaleOrLength: Int
    ) {
        setObject(parameterIndex, x)
    }

    @Throws(SQLException::class)
    override fun setAsciiStream(
        parameterIndex: Int,
        x: InputStream,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setBinaryStream(
        parameterIndex: Int,
        x: InputStream,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setCharacterStream(
        parameterIndex: Int,
        reader: Reader,
        length: Long
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setAsciiStream(
        parameterIndex: Int,
        x: InputStream
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setBinaryStream(
        parameterIndex: Int,
        x: InputStream
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setCharacterStream(
        parameterIndex: Int,
        reader: Reader
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNCharacterStream(
        parameterIndex: Int,
        value: Reader
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setClob(
        parameterIndex: Int,
        reader: Reader
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setBlob(
        parameterIndex: Int,
        inputStream: InputStream
    ) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun setNClob(
        parameterIndex: Int,
        reader: Reader
    ) {
        throw SQLFeatureNotSupportedException()
    }
}
