package com.wisecoders.jdbc.scylladb

import com.datastax.oss.driver.api.core.cql.BatchStatement
import com.datastax.oss.driver.api.core.cql.BatchType
import com.datastax.oss.driver.api.core.cql.SimpleStatement
import com.datastax.oss.driver.api.core.servererrors.SyntaxError
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLSyntaxErrorException

/**
 * Licensed under [CC BY-ND 4.0 DEED](https://creativecommons.org/licenses/by-nd/4.0/), copyright [Wise Coders GmbH](https://wisecoders.com), used by [DbSchema Database Designer](https://dbschema.com).
 * Code modifications allowed only as pull requests to the [public GIT repository](https://github.com/wise-coders/scylladb-jdbc-driver).
 */
class ScyllaDBStatement internal constructor(private val connection: ScyllaDBConnection) : ScyllaDBBaseStatement(
    connection.session
) {
    @Throws(SQLException::class)
    override fun executeQuery(sql: String): ResultSet {
        checkClosed()
        try {
            val _result = ScyllaDBResultSet(this, session.execute(sql))
            this.result = _result
            return _result
        } catch (ex: SyntaxError) {
            val rs = connection.executeDescribeCommand(sql)
            if (rs != null) {
                return rs
            }
            throw SQLSyntaxErrorException(ex.message, ex)
        } catch (t: Throwable) {
            throw SQLException(t.message, t)
        }
    }

    @Throws(SQLException::class)
    override fun executeUpdate(sql: String): Int {
        checkClosed()
        try {
            result = ScyllaDBResultSet(this, session.execute(sql))
            if (result!!.isQuery) {
                throw SQLException("Not an update statement")
            }
            return 1
        } catch (ex: SyntaxError) {
            throw SQLSyntaxErrorException(ex.message, ex)
        } catch (t: Throwable) {
            throw SQLException(t.message, t)
        }
    }

    @Throws(SQLException::class)
    override fun execute(sql: String): Boolean {
        checkClosed()
        try {
            return executeInner(session.execute(sql), true)
        } catch (t: Throwable) {
            throw SQLException(t.message, t)
        }
    }

    @Throws(SQLException::class)
    override fun getResultSet(): ResultSet? {
        checkClosed()
        return result
    }

    override fun addBatch(sql: String) {
        if (batchStatementBuilder == null) {
            batchStatementBuilder = BatchStatement.builder(BatchType.LOGGED)
        }
        batchStatementBuilder!!.addStatement(SimpleStatement.newInstance(sql))
    }

    override fun clearBatch() {
        batchStatementBuilder = null
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        autoGeneratedKeys: Int
    ): Int {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnIndexes: IntArray
    ): Int {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnNames: Array<String>
    ): Int {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        autoGeneratedKeys: Int
    ): Boolean {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnIndexes: IntArray
    ): Boolean {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnNames: Array<String>
    ): Boolean {
        throw SQLFeatureNotSupportedException()
    }
}
